#!bin/sh

HOST_NAME=`hostname`
STATUS=`curl -I "http://$HOST_NAME:25280/sherlock/intent?q=samsung" | grep "HTTP" | awk '{print $2}'`
ELB_HEALTHCHECK_API_STATUS=`curl -s -I "http://$HOST_NAME:25280/elb-healthcheck" | grep "HTTP" | awk '{print $2}'`

#VERSION_TO_DEPLOY="<%= @packageVersion %>"

CURRENT_ROTATION_STATUS="<%= @currentRotationStatus %>"

#NEW_VERSION=`dpkg -l | grep fk-w3-sherlock | awk '{print $3}'`

NEW_ROTATION_STATUS="`fk-w3-sherlock-admin status`"
SOLR_API="http://$HOST_NAME:25280/solr/admin/cores?action=STATUS&wt=json"

CORE_INIT_FAILURES=`curl -H "Accept: application/json" "$SOLR_API" | grep -Po '("initFailures":{})'`
CORE_SUCCESS_CRITERIA="\"initFailures\":{}"
echo "====================================================="
echo "Doing Health checks after package installation"
echo "====================================================="

if [ "$STATUS" = "200" ]
then
    echo "========curl command successful========"
    echo "status = $STATUS"
else
    echo "===========curl command failed=========="
    echo "status = $STATUS"
    exit 2
fi

if [ "$CURRENT_ROTATION_STATUS" = "In rotation" ]
then
    if [ "$ELB_HEALTHCHECK_API_STATUS" = "200" ]
    then
    echo "========curl elb health check command successful========"
    echo "status = $ELB_HEALTHCHECK_API_STATUS"
    else
    echo "===========curl elb health check command failed=========="
    echo "status = $ELB_HEALTHCHECK_API_STATUS"
    exit 2
    fi
else
    if [ "$ELB_HEALTHCHECK_API_STATUS" = "404" ]
    then
    echo "========curl elb health check command successful========"
    echo "status = $ELB_HEALTHCHECK_API_STATUS"
    else
    echo "===========curl elb health check command failed=========="
    echo "status = $ELB_HEALTHCHECK_API_STATUS"
    exit 2
    fi
fi


#if [ "$VERSION_TO_DEPLOY" = "$NEW_VERSION" ]
#then
#    echo "===package version check successful===="
#    echo "package version = $VERSION_TO_DEPLOY"
#else
#    echo "=====package version check failed======="
#    echo "Version_to_deploy=$VERSION_TO_DEPLOY   New_version=$NEW_VERSION"
#    exit 2
#fi


if [ "$CURRENT_ROTATION_STATUS" = "$NEW_ROTATION_STATUS" ]
then
    echo "====rotation status check successful==="
    echo "rotation status = $NEW_ROTATION_STATUS"
else
    echo "======rotation status check failed======"
    echo "current_rotation_status=$CURRENT_ROTATION_STATUS   New_rotation_status=$NEW_ROTATION_STATUS"
    exit 2
fi

if [ "$CORE_INIT_FAILURES" = "$CORE_SUCCESS_CRITERIA" ]
then
    echo "====core initialisation successful====="
    exit 0
else
    echo "======core initialisation failure======"
    echo "core_init_failures=$CORE_INIT_FAILURES  core_success_criteria=$CORE_SUCCESS_CRITERIA"
    exit 2
fi